### ISSUE TITLE
Have timer start after a button press

### ISSUE THREAD

**Issue by GeorgeIoak** [uniuno/timer#1]
I was experimenting with your library and I tried to have the timer start only after a button was pressed. In `void loop()` I start with `timer.tick()` and then later in the loop if a button press is detected I added `timer.attach_to_loop()` but the timer didn't start. I guess this makes sense since at then end of the loop I call `timer.detach_from_loop()`.

So how can you setup a timer but then maybe enable or disable it if you only want it's function call to happen sometimes?

**Comment by ttarnowski** [comment]
`attach_to_loop()` and `detach_from_loop()` methods are for general switching on/off the timer so all the timeouts and intervals you have set on it won't be executed.

I think in the case of your button example set_interval/clear_interval or set_timeout/clear_timeout combination would be more suitable. The way you'd do it is to set timeout/interval when button is pressed and clear it after something else happens or a timeout is reached.

```cpp
uniuno::Timer timer;
unsigned int blinkIntervalId;

void main() {
  timer.attach_to_loop();

  // some callback that will be called when button is clicked
  setOnButtonClick([]() { 
    // create 1 second interval that changes the digital LED_PIN state to opposite
    blinkIntervalId = timer.set_interval([]() {
      // blink every second
      digitalWrite(LED_PIN, digitalRead(LED_PIN) == 1 ? 0 : 1);
    }, 1000);

    // clear blink interval after 15 seconds
    timer.set_timeout([]() {
       clear_interval(blinkIntervalId);
    }, 15000);
  });
}

void loop() {
  timer.tick();
}

```

**Comment by GeorgeIoak** [comment]
In your example the blinking will stop after 15 seconds but if I just want to stop the blinking when some other code happens I can just issue a `timer.clear_interval(blinkIntervalId)` when I want the blinking to stop?

**Comment by ttarnowski** [comment]
yeah, that's right
